--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thurm64/CustomCrafting
build-by-default: true
branches:
- main
projects:
  CustomCrafting:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: muqsit/InvMenu/InvMenu
      branch: master
      version: ^3.1.0
...
